version: "3.9"
services:
  api-node-prod:
    image: api-node
    container_name: api-node-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    init: true
    env_file:
      - .env
    restart: unless-stopped